### ISSUE TITLE
[Discovery] "Submit correction" form broken.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1010]
**Bug Description and Replication**

<img width="561" alt="screen shot 2018-05-17 at 10 36 17 am" src="https://user-images.githubusercontent.com/1093066/40191267-2bd0e9d6-59be-11e8-84ae-a1445471f9d3.png">
<img width="744" alt="screen shot 2018-05-17 at 10 36 38 am" src="https://user-images.githubusercontent.com/1093066/40191284-35dee680-59be-11e8-99e2-58e6e3ec5f09.png">

Sending email is working in the application and on the production server, so the problem isn't with sending mail. We will have to look at the test or production logs (either in the application or in httpd) to see what's going wrong.

**Comment by redlibrarian** [comment]
I fixed the email problem, but now in production it's throwing an error. I hope to fix it before Friday, so it can go into production on Monday. / @theLinkResolver

**Comment by redlibrarian** [comment]
This is fixed now.

**Comment by theLinkResolver** [comment]
Not working again. "Something has gone wrong"

**Comment by redlibrarian** [comment]
I can't see what's going wrong, and it looks like it's working in test. I've asked @nmacgreg to take a look.

**Comment by redlibrarian** [comment]
Still broken...

**Comment by redlibrarian** [comment]
Done when:

- [ ] Send correction form working again. This may be something on the server side...

**Comment by redlibrarian** [comment]
I think I fixed the underlying problem in the NEOS Discovery project, though these may be unrelated as the Blacklight version is different between the two projects ( see https://github.com/ualbertalib/NEOSDiscovery/commit/79f3429ad12ef9f352462dba9a8216485a67d090)

**Comment by weiweishi** [comment]
Could be a server/firewall configuration issue. Still doesn't work for NEOS instance for off-campus mail. That issue should be looked into first.

**Comment by seanluyk** [comment]
Not sure if this is actually fixed, so reopening this issue

**Comment by theLinkResolver** [comment]
It's fair to add the comment, for the sake of the developers who are new to the project, that issues with "send correction" have been a persistent issue. There are likely numerous issues (open or closed) that can be searched in here that document the various attempts to resolve this.

**Comment by seanluyk** [comment]
Adding a test link for reference as this error oddly doesn't occur with all records in discovery:

1. This one doesn't work: https://library.ualberta.ca/catalog/469895

2. This one does: https://library.ualberta.ca/catalog/2117026

**Comment by weiweishi** [comment]
- will try to replicate this on the dev env. 
- need to access the log to debug

**Comment by seanluyk** [comment]
Just tried my examples above - the ones that don't work do in an incognito window

**Comment by murny** [comment]
Closing issue. Feel free to reopen if problem persists
