### ISSUE TITLE
Collection: Microguide

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1054]

**Comment by redlibrarian** [comment]
Done when:

- [ ] Traject rules in place
- [ ] Records indexed
- [ ] Appropriate views built

I haven't looked closely at these records. My understanding is that this is a static (non-updating collection).

**Comment by theLinkResolver** [comment]
@redlibrarian I can confrim these records do still get updates and edits.

**Comment by redlibrarian** [comment]
Ah, OK - thanks, Scott.

**Comment by redlibrarian** [comment]
https://microguide.library.ualberta.ca/index.cfm

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
