### ISSUE TITLE
Fix diacritics font issues

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1268]
Characters with diacritics have the appearance of being bolded in facet lists, search results, and record views. Some examples from UAT:

**Search Results**
http://uat.library.ualberta.ca:3002/catalog?q=music

**Facet Lists**
![capture](https://user-images.githubusercontent.com/14880206/45505582-2c177d80-b74a-11e8-8cfd-c12f8823ec61.PNG)

**Record Views**
http://uat.library.ualberta.ca:3002/catalog/kule465339893
 - In title, contents notes, etc.

**Comment by nnunn** [comment]
This was a font issue. I have fixed it.

**Comment by seanluyk** [comment]
Not sure if this is fixed at the record view level, e.g.: https://library.ualberta.ca/catalog/2774952

**Comment by seanluyk** [comment]
@pgwillia @weiweishi this issue still persists and is hopefully an easier change now with the CMS removed and CSS cleaned up?

**Comment by theLinkResolver** [comment]
Here's a record with syllabics to also keep an eye on: https://search.library.ualberta.ca/catalog/8273061

On my screen i'm not certain if these are bold or not but hopefully this is helpful for testing any font tweakage

**Comment by seanluyk** [comment]
@theLinkResolver for what it's worth, that record looks pretty good to me, but good to keep in mind
