### ISSUE TITLE
Bento Box - Containers

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#555]
These are likely design choices (and I understand huge to change), but I'm passing on some feedback from HSS colleagues regarding the logic of the bento box containers:

1. *Books and More* and *Ebooks and More* should be combined, as users are searching for specific content first, and limiting by format later (or at least we would like them to :). It might send the wrong message to separate formats this way, as we want users to find the best sources possible, regardless of what format we own them in.  

2. Electronic Journals ideally would include both print and electronic journals, again, because it's about content, not format. It's also confusing to the user as they may think that print journal results are not included in this container, so don't know where to click as the item is not a book, etc. It may also be worth considering relabeling this container as "Journals and Periodicals" to be more accurate.

**Comment by seanluyk** [comment]
I think this has been completed. OK to close?

**Comment by redlibrarian** [comment]
Yes, thanks.

**Comment by theLinkResolver** [comment]
I'm still seeing the Symphony print + electronic records in Books/Media/More pane, and only SFX records in the Journals pane.

e.g. https://search.library.ualberta.ca/results?utf8=%3F&q=germanic+review

**Comment by redlibrarian** [comment]
The Books/Media/More pane is suppose to contain print and electronic, no? Wasn't that the reason for getting rid of the ebooks pane?

As for the journals, I think this is a different problem. It should be fixed in the next release.

**Comment by sjshores** [comment]
Yes, I think this is what is now supposed to be in the Books, Media and
More pane.

Sandra

**Comment by theLinkResolver** [comment]
@redlibrarian @sjshores Sorry - left out a very important word! I'm still seeing the Symphony print + electronic SERIAL records in the Books/Media/More pane.

I thought all the serial Symphony records were moving to the Journals pane (where the records with SFX object IDs in the 940 field would be filtered out in favour of the SFX records.
