### ISSUE TITLE
Advanced search is broken

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#654]
I've been noticing some issues in the advanced search. It redirects to a "something has gone wrong" page from some all field searches.

For example...

1. Search for Henle in all fields

**Comment by seanluyk** [comment]
I'm not seeing any EDS results returned in advanced searches at all actually, just Symphony results.

**Comment by redlibrarian** [comment]
The bug has been fixed, and should work in the next release.

As for EDS results - the default advanced search only returns local index results (Symphony, SFX, databases). For article advanced search, you have to use the other link. Does that help @seanluyk or am I misunderstanding your second comment?

**Comment by seanluyk** [comment]
@redlibrarian you can ignore my second comment, I forgot that only local index results appear.

**Comment by seanluyk** [comment]
The initial issue is not recurring, but advanced search still does not appear to be working. Any term searched in **All Fields** returns 5,697,787 results

**Comment by redlibrarian** [comment]
See #719

**Comment by redlibrarian** [comment]
This should be working now. @seanluyk can you verify?

**Comment by seanluyk** [comment]
This is working great now, so I'll close the issue. I'm also noticing that much fewer irrelevant results are appearing, which is great!
